#!/bin/sh

# script to pipe links from st into dmenu

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr '\n' ' ' | # flatten output
  grep -aEo "$urlregex" |              # extract URLs
  uniq |                               # remove duplicates
  sed -E "s/[\.,;!?]$//; s/^www./http:\/\/www./")"

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do case "${o}" in
  h) printf "Optional arguments for custom use:\\n  -c: copy\\n  -o: xdg-open\\n  -h: Show this message\\n" && exit 1 ;;
  o)
    chosen="$(echo "$urls" | dmenu -i -p 'Follow which url?' -l 10)"
    setsid xdg-open "$chosen" >/dev/null 2>&1 &
    ;;
  c) echo "$urls" | dmenu -i -p 'Copy which url?' -l 10 | tr -d '\n' | xclip -selection clipboard ;;
  *) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
  esac done
